version: '3.8'

x-build: &ekatrafl_build
  build:
    context: .
    dockerfile: Dockerfile
  image: unifyfl

services:
  train_container_0:
    image: unifyfl
    environment:
      - TRAIN_SET=0
    mem_limit: 1g
    restart: no
    network_mode: "host"

  train_container_1:
    image: unifyfl
    environment:
      - TRAIN_SET=1
    mem_limit: 1g
    restart: no
    network_mode: "host"

  train_container_2:
    image: unifyfl
    environment:
      - TRAIN_SET=2
    mem_limit: 1g
    restart: no
    network_mode: "host"

  train_container_3:
    image: unifyfl
    environment:
      - TRAIN_SET=3
    mem_limit: 1g
    restart: no
    network_mode: "host"
